# Generated by Django 4.2.11 on 2024-04-07 11:07

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_management', '0003_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='petprofile',
            name='pet_picture',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
