# Generated by Django 4.2.11 on 2024-04-07 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kennel_manager', '0006_remove_booking_pet_name_booking_num_pets'),
        ('account_management', '0004_petprofile_pet_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PetProfile',
        ),
    ]
