# Generated by Django 4.2.11 on 2024-03-27 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kennel_manager', '0002_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='kennel',
            name='spaces',
            field=models.IntegerField(),
            preserve_default=False,
        ),
    ]
