# Generated by Django 4.2.11 on 2024-03-27 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_management', '0002_petprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kennel_manager', '0003_kennel_spaces'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='status',
        ),
        migrations.AlterField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='booking',
            name='pet_name',
        ),
        migrations.AddField(
            model_name='booking',
            name='pet_name',
            field=models.ManyToManyField(to='account_management.petprofile'),
        ),
    ]
