# Generated by Django 4.2.11 on 2024-04-06 10:41

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kennel_manager', '0004_remove_booking_status_alter_booking_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kennel',
            name='kennel_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='kennel',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
