# Generated by Django 4.2.11 on 2024-04-07 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kennel_manager', '0005_kennel_kennel_image_alter_kennel_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='pet_name',
        ),
        migrations.AddField(
            model_name='booking',
            name='num_pets',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
